enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[YouTube-inotia00]
enabled = false
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced inotia00"
build-mode = "both"
version = "19.16.39"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music-inotia00]
enabled = false
app-name = "Music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced inotia00"
build-mode = "both"
arch = "arm64-v8a"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Custom header for YouTube Music'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[YouTube-anddea]
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced anddea"
build-mode = "both"
version = "19.16.39"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom header for YouTube'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music-anddea]
app-name = "Music"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced anddea"
build-mode = "both"
arch = "arm64-v8a"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Custom header for YouTube Music'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[YouTube-MorpheApp]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
excluded-patches = "'Custom branding' 'Change header'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music-MorpheApp]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
arch = "arm64-v8a"
excluded-patches = "'Custom branding' 'Change header'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
